name: tensorflow Release

on: 
  release:
    types: [push]

jobs:

  release:
    name: build Tensorflow Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: apt install python3 python3-dev python3-pip curl
    - name: Install dependencies 2 
      run: pip install -U --user pip six numpy wheel setuptools mock 'future>=0.17.1'  
    - name: Install dependencies 3 
      run: pip install -U --user keras_applications --no-deps
    - name: Install dependencies 4 
      run: pip install -U --user keras_preprocessing --no-deps
    - name: Install dependencies bazel 
      run: curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add - ;echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list;sudo apt update && sudo apt install bazel
    - name: Install dependencies checkout 
      run: git checkout r2.1
     - name: build 
      run: ./configure --config=mkl;bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
     - name: Archive
      run: tar -czf Release.tar.gz /tmp/* 
    - name: Upload all Release
      uses: JasonEtco/upload-to-release@master
      with:
        args: Release.tar.gz application/x-gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
