# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tensorflow whl Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U --user pip six numpy wheel setuptools mock 'future>=0.17.1'
        pip install -U --user keras_applications --no-deps
        pip install -U --user keras_preprocessing --no-deps
    - name: Install dependencies bazel
      run: |
        curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
        echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        sudo apt update
        sudo apt install bazel
    - name: build tensorflow
      run: |
        ./configure
        bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
    - name: Archive
      run: tar -czf Release.tar.gz /tmp/* 
    - name: Upload all Release
      uses: JasonEtco/upload-to-release@master
      with:
        args: Release.tar.gz application/x-gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
